// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangepasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changepassword() {
    driver.get("http://research.mawashi.tools:8080/login");
    driver.manage().window().setSize(new Dimension(843, 710));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("testuser");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("asdffdsA1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".treeview:nth-child(6) .fa-angle-left")).click();
    driver.findElement(By.linkText("Profile")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("asdffdsA1");
    driver.findElement(By.id("password_confirm")).click();
    driver.findElement(By.id("password_confirm")).sendKeys("asdffdsA1");
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
  }
}
